import {
  type Pessoa,
  emptyProprietary, emptyEmployee, emptyProvider, emptyClient, emptyUser,
} from './pessoas.types'

/**
 * Dados de exemplo do módulo Pessoas Unificado. Cobrem combinações variadas de
 * papéis: pessoa com papel único, múltiplos papéis, PF e PJ, ativos e inativos.
 */
export const mockPessoas: Pessoa[] = [
  {
    id: 1,
    nif: '12345678909',
    name: 'João Pereira',
    nickname: 'João Pereira',
    email: 'joao.pereira@fazendasaojoao.com.br',
    phone: '65999887766',
    cityId: 'sor',
    zipCode: '78890000',
    address: 'Rodovia BR-163, km 720',
    number: 'S/N',
    district: 'Zona Rural',
    proprietary: { enabled: true, inscricoes: ['1234567890'], farms: [{ farmId: 'f1', percentage: '60' }, { farmId: 'f3', percentage: '100' }] },
    employee: emptyEmployee(),
    provider: emptyProvider(),
    client: emptyClient(),
    user: { ...emptyUser(), enabled: true, roleIds: ['admin'], farmIds: ['f1', 'f3'] },
  },
  {
    id: 2,
    nif: '98765432100',
    name: 'Maria Santos',
    nickname: 'Maria S.',
    email: 'maria.santos@email.com',
    phone: '65988776655',
    cityId: 'cba',
    zipCode: '78005000',
    address: 'Av. Historiador Rubens de Mendonça',
    number: '1856',
    district: 'Bosque da Saúde',
    proprietary: emptyProprietary(),
    employee: { ...emptyEmployee(), enabled: true, office: 'Operadora de máquinas', functionId: '6410', centerId: 'cc1', baseSalary: '2800,00', bankId: '341', accountType: 'C', agency: '0123', account: '45678-9', pixType: 'cpfcnpj', pix: '987.654.321-00', birthday: '1990-05-14' },
    provider: emptyProvider(),
    client: emptyClient(),
    user: emptyUser(),
  },
  {
    id: 3,
    nif: '11222333000181',
    name: 'AgroInsumos do Cerrado',
    nickname: 'AgroInsumos do Cerrado LTDA',
    email: 'contato@agroinsumos.com.br',
    phone: '6233445566',
    cityId: 'rvd',
    zipCode: '75901970',
    address: 'Av. Presidente Vargas',
    number: '2200',
    district: 'Centro',
    proprietary: emptyProprietary(),
    employee: emptyEmployee(),
    provider: {
      ...emptyProvider(), enabled: true, type: '1', stateRegistration: '10.123.456-7',
      cityRegistration: '55.123', contact: 'Fernando Lima', contactPhone: '62988112233',
      bankId: '001', accountType: 'C', agency: '4567', account: '12345-6', pixType: 'email', pix: 'financeiro@agroinsumos.com.br',
      branches: [{ nif: '11222333000262', stateRegistration: '10.987.654-3', zipCode: '78890000', address: 'Rua das Acácias, 100', cityId: 'sor' }],
      sellers: [{ name: 'Patrícia Gomes', email: 'patricia@agroinsumos.com.br', phone: '62977665544' }],
    },
    client: emptyClient(),
    user: emptyUser(),
  },
  {
    id: 4,
    nif: '44555666000199',
    name: 'Cooperativa Grãos Unidos',
    nickname: 'Coop. Grãos Unidos',
    email: 'compras@graosunidos.coop.br',
    phone: '4333221100',
    cityId: 'ldb',
    zipCode: '86010000',
    address: 'Av. Tiradentes',
    number: '4500',
    district: 'Jardim Shangri-lá',
    proprietary: emptyProprietary(),
    employee: emptyEmployee(),
    provider: emptyProvider(),
    client: {
      ...emptyClient(), enabled: true, cellphone: '43999001122', contact: 'Setor de Compras',
      contactPhone: '4333221100', taxpayer: true, finalConsumer: false, countryId: 'BR',
      farmName: 'Unidade Armazenadora Norte', stateRegistrations: ['90.123.456-78'], cityRegistration: '12345',
    },
    user: emptyUser(),
  },
  {
    id: 5,
    nif: '32165498700',
    name: 'Carlos Andrade',
    nickname: 'Carlos Andrade',
    email: 'carlos.andrade@grupogb.com.br',
    phone: '65991002030',
    cityId: 'cba',
    zipCode: '78048000',
    address: 'Rua das Palmeiras',
    number: '321',
    district: 'Jardim das Américas',
    proprietary: { enabled: true, inscricoes: [], farms: [{ farmId: 'f2', percentage: '50' }] },
    employee: { ...emptyEmployee(), enabled: true, office: 'Gerente de produção', functionId: '1423', centerId: 'cc3', baseSalary: '9500,00', goalSalary: '12000,00', bankId: '237', accountType: 'C', agency: '0987', account: '11223-4', pixType: 'phone', pix: '65991002030', birthday: '1982-11-02' },
    provider: emptyProvider(),
    client: emptyClient(),
    user: { ...emptyUser(), enabled: true, purchasingAssistant: true, roleIds: ['manager'], farmIds: ['f2'] },
  },
  {
    id: 6,
    nif: '77888999000150',
    name: 'TransRural Logística',
    nickname: 'TransRural Logística ME',
    email: 'operacao@transrural.com',
    phone: '6230011223',
    cityId: 'rvd',
    zipCode: '75905000',
    address: 'Distrito Industrial, Quadra 5',
    number: '12',
    district: 'DAIRV',
    proprietary: emptyProprietary(),
    employee: emptyEmployee(),
    provider: { ...emptyProvider(), enabled: false, type: '4', branches: [], sellers: [] },
    client: { ...emptyClient(), enabled: true, taxpayer: false, finalConsumer: true, countryId: 'BR', stateRegistrations: [] },
    user: emptyUser(),
  },
]
