import type { FazendaRow, FazendaDetalheData } from './fazendas.types'

export const mockFazendas: FazendaRow[] = [
  {
    id: '1',
    nome: 'Fazenda Santa Luzia',
    cpfCnpj: '12.345.678/0001-90',
    cidade: 'Sorriso',
    uf: 'MT',
    tipoExploracao: 'Agrícola',
    areaTotal: 2450,
    ativo: true,
  },
  {
    id: '2',
    nome: 'Fazenda Bela Vista',
    cpfCnpj: '987.654.321-00',
    cidade: 'Rondonópolis',
    uf: 'MT',
    tipoExploracao: 'Pecuário',
    areaTotal: 1800,
    ativo: true,
  },
  {
    id: '3',
    nome: 'Fazenda Cerrado Verde',
    cpfCnpj: '23.456.789/0001-11',
    cidade: 'Rio Verde',
    uf: 'GO',
    tipoExploracao: 'Agrícola',
    areaTotal: 3200,
    ativo: true,
  },
  {
    id: '4',
    nome: 'Fazenda Três Irmãos',
    cpfCnpj: '876.543.210-99',
    cidade: 'Jataí',
    uf: 'GO',
    tipoExploracao: 'Misto',
    areaTotal: 950,
    ativo: false,
  },
  {
    id: '5',
    nome: 'Fazenda Pantanal Sul',
    cpfCnpj: '34.567.890/0001-22',
    cidade: 'Cáceres',
    uf: 'MT',
    tipoExploracao: 'Pecuário',
    areaTotal: 2100,
    ativo: true,
  },
  {
    id: '6',
    nome: 'Fazenda Horizonte',
    cpfCnpj: '765.432.109-88',
    cidade: 'Uberaba',
    uf: 'MG',
    tipoExploracao: 'Misto',
    areaTotal: 680,
    ativo: true,
  },
  {
    id: '7',
    nome: 'Fazenda São Benedito',
    cpfCnpj: '45.678.901/0001-33',
    cidade: 'Uberlândia',
    uf: 'MG',
    tipoExploracao: 'Agrícola',
    areaTotal: 1250,
    ativo: false,
  },
  {
    id: '8',
    nome: 'Fazenda Nova Esperança',
    cpfCnpj: '654.321.098-77',
    cidade: 'Primavera do Leste',
    uf: 'MT',
    tipoExploracao: 'Agrícola',
    areaTotal: 1750,
    ativo: true,
  },
]

export interface CentroCusto {
  id: string
  codigo: string
  classe: 'Analítica' | 'Sintética'
  condicao: 'Ambos' | 'Receita' | 'Despesa'
  descricao: string
}

export const mockFazendaSantaLuzia: FazendaDetalheData = {
  id: '1',
  nome: 'Fazenda Santa Luzia',
  cpfCnpj: '12.345.678/0001-90',
  inscricaoEstadual: '903.456.788.342',
  telefone: '(66) 98765-4321',
  tipoExploracao: 'Agrícola',
  car: 'MT-5107305-6D3F4A2B8C9E1F0A7D3B5C2E4F6A8B0',
  nirf: '5.432.901-7',
  ccir: '843.751.006.890-4',
  cafir: '07.345.678-2',
  caepi: 'MT-12345/2019',
  pais: 'Brasil',
  cep: '78890-000',
  cidade: 'Sorriso',
  uf: 'MT',
  endereco: 'Rodovia BR-163',
  numero: 'KM 742',
  bairro: 'Zona Rural',
  latitude: '-12.5436',
  longitude: '-55.7215',
  moeda: 'BRL',
  areaTotal: 2450,
  valorHa: 28500,
  taxaRemuneracao: 6.5,
  ativo: true,
  usoLivroCaixa: true,
  centrosCusto: [
    { id: 'cc1', codigo: '1.01.001', classe: 'Analítica', condicao: 'Ambos',   descricao: 'Centro Custo/Apropriar' },
    { id: 'cc3', codigo: '1.02.001', classe: 'Analítica', condicao: 'Ambos',   descricao: 'Soja' },
    { id: 'cc4', codigo: '1.02.002', classe: 'Analítica', condicao: 'Ambos',   descricao: 'Milho' },
    { id: 'cc10', codigo: '1.04.002', classe: 'Analítica', condicao: 'Despesa', descricao: 'Combustível e Lubrificantes' },
    { id: 'cc11', codigo: '1.05.001', classe: 'Analítica', condicao: 'Receita', descricao: 'Venda de Grãos' },
  ],
  observacao: 'Propriedade com certificação de boas práticas agrícolas. Safra principal: soja. Safra secundária: milho. Área de preservação permanente regularizada junto ao IBAMA.',
}

export const mockCentrosCusto: CentroCusto[] = [
  { id: 'cc1', codigo: '1.01.001', classe: 'Analítica', condicao: 'Ambos', descricao: 'Centro Custo/Apropriar' },
  { id: 'cc2', codigo: '1.01.002', classe: 'Analítica', condicao: 'Despesa', descricao: 'Administração Geral' },
  { id: 'cc3', codigo: '1.02.001', classe: 'Analítica', condicao: 'Ambos', descricao: 'Soja' },
  { id: 'cc4', codigo: '1.02.002', classe: 'Analítica', condicao: 'Ambos', descricao: 'Milho' },
  { id: 'cc5', codigo: '1.02.003', classe: 'Analítica', condicao: 'Ambos', descricao: 'Algodão' },
  { id: 'cc6', codigo: '1.02.004', classe: 'Analítica', condicao: 'Ambos', descricao: 'Cana-de-açúcar' },
  { id: 'cc7', codigo: '1.03.001', classe: 'Analítica', condicao: 'Ambos', descricao: 'Pecuária de Corte' },
  { id: 'cc8', codigo: '1.03.002', classe: 'Analítica', condicao: 'Ambos', descricao: 'Pecuária de Leite' },
  { id: 'cc9', codigo: '1.04.001', classe: 'Sintética', condicao: 'Despesa', descricao: 'Manutenção de Máquinas' },
  { id: 'cc10', codigo: '1.04.002', classe: 'Analítica', condicao: 'Despesa', descricao: 'Combustível e Lubrificantes' },
  { id: 'cc11', codigo: '1.05.001', classe: 'Analítica', condicao: 'Receita', descricao: 'Venda de Grãos' },
  { id: 'cc12', codigo: '1.05.002', classe: 'Analítica', condicao: 'Receita', descricao: 'Venda de Animais' },
]
