/**
 * GB CERNE — Registry de ícones
 *
 * Único ponto do projeto que conhece a biblioteca de ícones. Telas e componentes
 * referenciam `IconName` (papel), nunca o nome do desenho — trocar o ícone de um
 * papel em toda a aplicação é editar uma linha aqui (Lei 2).
 *
 * Família: HugeIcons (stroke-rounded) — traço 1.5 nativo em grade 24.
 * Espessura e tamanho saem de `t.stroke.icon` / `t.size.icon` via `<Icon>`.
 *
 * Ícone novo: adicione o import e uma entrada com nome de PAPEL (o que ele
 * significa: `delete`, `harvest`), nunca o nome do desenho (`Delete02Icon`).
 */

import {
  Activity03Icon,
  Alert02Icon,
  AlertCircleIcon,
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowLeft02Icon,
  ArrowLeftRightIcon,
  ArrowRight01Icon,
  ArrowRight02Icon,
  ArrowUp01Icon,
  ArrowUpRight01Icon,
  BanknoteIcon,
  BarChartIcon,
  BeefIcon,
  BlendIcon,
  BlocksIcon,
  BookOpen01Icon,
  BoxesIcon,
  Briefcase01Icon,
  Building02Icon,
  CalculatorIcon,
  Calendar03Icon,
  CalendarCheckIcon,
  CalendarClockIcon,
  CalendarXIcon,
  Camera01Icon,
  Cancel01Icon,
  ChartColumnIcon,
  ChartLineIcon,
  CheckmarkCircle01Icon,
  CheckmarkCircle02Icon,
  CheckmarkSquare01Icon,
  CircleArrowDown01Icon,
  CircleArrowUp01Icon,
  CircleIcon,
  CircleXIcon,
  ClipboardCheckIcon,
  ClipboardListIcon,
  Clock01Icon,
  Clock03Icon,
  CloudIcon,
  CloudRainIcon,
  ConstructionIcon,
  ContactIcon,
  Copy01Icon,
  CreditCardIcon,
  CrownIcon,
  DashboardSquare01Icon,
  Delete02Icon,
  DollarSignIcon,
  Download04Icon,
  DropletsIcon,
  Exchange01Icon,
  ExternalLinkIcon,
  FactoryIcon,
  FenceIcon,
  FileCheckIcon,
  FileCodeIcon,
  FileInputIcon,
  FileKeyIcon,
  FilePlusIcon,
  FileSearchIcon,
  FileSpreadsheetIcon,
  FileTextIcon,
  FileTypeIcon,
  Files01Icon,
  FilterHorizontalIcon,
  FilterIcon,
  FlaskConicalIcon,
  FloppyDiskIcon,
  FolderOpenIcon,
  FuelIcon,
  GaugeIcon,
  GemIcon,
  GitBranchIcon,
  GitBranchPlusIcon,
  GitCompareIcon,
  GitMergeIcon,
  GlobeIcon,
  GridViewIcon,
  GripVerticalIcon,
  HandshakeIcon,
  HardHatIcon,
  HashIcon,
  HeartIcon,
  HelpCircleIcon,
  Home01Icon,
  ImagePlusIcon,
  InboxIcon,
  InformationCircleIcon,
  Key01Icon,
  LandmarkIcon,
  Layers01Icon,
  LifebuoyIcon,
  Link02Icon,
  ListChecksIcon,
  ListIcon,
  ListPlusIcon,
  ListTreeIcon,
  Loading03Icon,
  Location01Icon,
  LockIcon,
  Login01Icon,
  Logout01Icon,
  MapPinOffIcon,
  MapsIcon,
  MessageCircleIcon,
  MinusSignIcon,
  MoonIcon,
  MoreHorizontalIcon,
  MoreVerticalIcon,
  NetworkIcon,
  Notification01Icon,
  Package02Icon,
  PackageCheckIcon,
  PackageIcon,
  PackageMinusIcon,
  PackageOpenIcon,
  PanelLeftCloseIcon,
  PenLineIcon,
  PencilEdit02Icon,
  PercentIcon,
  PieChartIcon,
  PlusSignIcon,
  PowerIcon,
  PrinterIcon,
  ReceiptIcon,
  ReceiptTextIcon,
  RefreshCwIcon,
  RepeatIcon,
  RotateCcwIcon,
  RotateCwIcon,
  Route01Icon,
  RowsThreeIcon,
  RulerIcon,
  ScaleIcon,
  Search01Icon,
  SearchXIcon,
  SecurityCheckIcon,
  Settings01Icon,
  Settings02Icon,
  Share08Icon,
  Shield01Icon,
  ShieldAlertIcon,
  ShoppingBag01Icon,
  ShoppingCart01Icon,
  SignatureIcon,
  SparklesIcon,
  SproutIcon,
  StarIcon,
  Sun03Icon,
  SunCloud01Icon,
  TableIcon,
  Tag01Icon,
  Target01Icon,
  Tick02Icon,
  Timer01Icon,
  TrendingDownIcon,
  TrendingUpIcon,
  TruckIcon,
  Undo02Icon,
  Upload04Icon,
  UserCheck01Icon,
  UserMultipleIcon,
  UserSettings01Icon,
  UtensilsIcon,
  ViewIcon,
  ViewOffIcon,
  Wallet01Icon,
  WarehouseIcon,
  WheatIcon,
  Wifi01Icon,
  Wrench01Icon,
} from '@hugeicons/core-free-icons'

export const icons = {
  // ── Ações
  'edit':             PencilEdit02Icon,
  'edit-line':        PenLineIcon,
  'add':              PlusSignIcon,
  'remove':           MinusSignIcon,
  'delete':           Delete02Icon,
  'view':             ViewIcon,
  'view-off':         ViewOffIcon,
  'save':             FloppyDiskIcon,
  'copy':             Copy01Icon,
  'close':            Cancel01Icon,
  'check':            Tick02Icon,
  'search':           Search01Icon,
  'search-empty':     SearchXIcon,
  'filter':           FilterIcon,
  'filter-advanced':  FilterHorizontalIcon,
  'download':         Download04Icon,
  'upload':           Upload04Icon,
  'print':            PrinterIcon,
  'share':            Share08Icon,
  'external-link':    ExternalLinkIcon,
  'link':             Link02Icon,
  'more-vertical':    MoreVerticalIcon,
  'more-horizontal':  MoreHorizontalIcon,
  'drag-handle':      GripVerticalIcon,
  'rotate':           RotateCwIcon,
  'rotate-back':      RotateCcwIcon,
  'refresh':          RefreshCwIcon,
  'repeat':           RepeatIcon,
  'undo':             Undo02Icon,
  'settings':         Settings01Icon,
  'settings-sliders': Settings02Icon,
  'power':            PowerIcon,
  'login':            Login01Icon,
  'logout':           Logout01Icon,

  // ── Navegação
  'arrow-left':        ArrowLeft02Icon,
  'arrow-right':       ArrowRight02Icon,
  'arrow-up-right':    ArrowUpRight01Icon,
  'arrow-up-circle':   CircleArrowUp01Icon,
  'arrow-down-circle': CircleArrowDown01Icon,
  'arrow-left-right':  ArrowLeftRightIcon,
  'transfer':          Exchange01Icon,
  'chevron-left':      ArrowLeft01Icon,
  'chevron-right':     ArrowRight01Icon,
  'chevron-up':        ArrowUp01Icon,
  'chevron-down':      ArrowDown01Icon,
  'sidebar-collapse':  PanelLeftCloseIcon,

  // ── Feedback
  'warning':      Alert02Icon,
  'alert':        AlertCircleIcon,
  'info':         InformationCircleIcon,
  'help':         HelpCircleIcon,
  'success':      CheckmarkCircle02Icon,
  'check-circle': CheckmarkCircle01Icon,
  'error':        CircleXIcon,
  'check-square': CheckmarkSquare01Icon,
  'circle':       CircleIcon,
  'loading':      Loading03Icon,

  // ── Campo e produção
  'grain':        WheatIcon,
  'sprout':       SproutIcon,
  'water':        DropletsIcon,
  'rain':         CloudRainIcon,
  'cloud':        CloudIcon,
  'cloud-sun':    SunCloud01Icon,
  'sun':          Sun03Icon,
  'moon':         MoonIcon,
  'fence':        FenceIcon,
  'cattle':       BeefIcon,
  'nutrition':    UtensilsIcon,
  'lab':          FlaskConicalIcon,
  'safety':       HardHatIcon,
  'truck':        TruckIcon,
  'warehouse':    WarehouseIcon,
  'factory':      FactoryIcon,
  'fuel':         FuelIcon,
  'ruler':        RulerIcon,
  'scale':        ScaleIcon,
  'target':       Target01Icon,
  'location':     Location01Icon,
  'location-off': MapPinOffIcon,
  'map':          MapsIcon,
  'globe':        GlobeIcon,
  'route':        Route01Icon,
  'network':      NetworkIcon,

  // ── Entidades
  'building':      Building02Icon,
  'home':          Home01Icon,
  'users':         UserMultipleIcon,
  'user-check':    UserCheck01Icon,
  'user-settings': UserSettings01Icon,
  'contact':       ContactIcon,
  'briefcase':     Briefcase01Icon,
  'handshake':     HandshakeIcon,
  'crown':         CrownIcon,
  'gem':           GemIcon,
  'star':          StarIcon,
  'heart':         HeartIcon,

  // ── Financeiro
  'wallet':         Wallet01Icon,
  'currency':       DollarSignIcon,
  'banknote':       BanknoteIcon,
  'credit-card':    CreditCardIcon,
  'receipt':        ReceiptIcon,
  'receipt-detail': ReceiptTextIcon,
  'bank':           LandmarkIcon,
  'calculator':     CalculatorIcon,
  'percent':        PercentIcon,
  'cart':           ShoppingCart01Icon,
  'shopping-bag':   ShoppingBag01Icon,

  // ── Estoque
  'package':       PackageIcon,
  'package-alt':   Package02Icon,
  'package-check': PackageCheckIcon,
  'package-open':  PackageOpenIcon,
  'package-minus': PackageMinusIcon,
  'stock':         BoxesIcon,
  'layers':        Layers01Icon,

  // ── Documentos
  'document':        FileTextIcon,
  'document-add':    FilePlusIcon,
  'document-check':  FileCheckIcon,
  'document-search': FileSearchIcon,
  'document-key':    FileKeyIcon,
  'document-code':   FileCodeIcon,
  'document-import': FileInputIcon,
  'document-type':   FileTypeIcon,
  'signature':       SignatureIcon,
  'spreadsheet':     FileSpreadsheetIcon,
  'documents':       Files01Icon,
  'folder':          FolderOpenIcon,
  'inbox':           InboxIcon,
  'clipboard-list':  ClipboardListIcon,
  'clipboard-check': ClipboardCheckIcon,
  'book':            BookOpen01Icon,
  'table':           TableIcon,
  'list':            ListIcon,
  'list-add':        ListPlusIcon,
  'list-checks':     ListChecksIcon,
  'list-tree':       ListTreeIcon,
  'rows':            RowsThreeIcon,

  // ── Dashboard e gráficos
  'dashboard':    DashboardSquare01Icon,
  'grid':         GridViewIcon,
  'chart-bar':    BarChartIcon,
  'chart-column': ChartColumnIcon,
  'chart-line':   ChartLineIcon,
  'chart-pie':    PieChartIcon,
  'gauge':        GaugeIcon,
  'activity':     Activity03Icon,
  'trend-up':     TrendingUpIcon,
  'trend-down':   TrendingDownIcon,

  // ── Tempo
  'calendar':       Calendar03Icon,
  'calendar-check': CalendarCheckIcon,
  'calendar-clock': CalendarClockIcon,
  'calendar-off':   CalendarXIcon,
  'clock':          Clock01Icon,
  'clock-alt':      Clock03Icon,
  'timer':          Timer01Icon,

  // ── Segurança
  'lock':         LockIcon,
  'key':          Key01Icon,
  'shield':       Shield01Icon,
  'shield-check': SecurityCheckIcon,
  'shield-alert': ShieldAlertIcon,

  // ── Comunicação
  'bell':    Notification01Icon,
  'message': MessageCircleIcon,
  'support': LifebuoyIcon,

  // ── Versionamento
  'git-branch':     GitBranchIcon,
  'git-branch-add': GitBranchPlusIcon,
  'git-merge':      GitMergeIcon,
  'git-compare':    GitCompareIcon,

  // ── Diversos
  'camera':       Camera01Icon,
  'image-add':    ImagePlusIcon,
  'sparkles':     SparklesIcon,
  'hash':         HashIcon,
  'tag':          Tag01Icon,
  'blocks':       BlocksIcon,
  'blend':        BlendIcon,
  'construction': ConstructionIcon,
  'wrench':       Wrench01Icon,
  'wifi':         Wifi01Icon,
} as const

/** Nome de papel de um ícone do sistema. */
export type IconName = keyof typeof icons
