import type { Conta } from './planoContas.types'

// ─── Mock — estrutura clássica de plano de contas ─────────────────────────────

export const mockPlanoContas: Conta[] = [
  { id: 1,  codigo: '1',       descricao: 'Receitas',                      condicao: 'credito', classe: 'sintetica', ativo: 'sim', tipo: '',      antecessorId: null, categorias: [],                  dataCriacao: '2026-01-05', usuarioCriacao: 'Silvio Ventura' },
  { id: 2,  codigo: '1.1',     descricao: 'Receitas da Agricultura',       condicao: 'credito', classe: 'sintetica', ativo: 'sim', tipo: '',      antecessorId: 1,    categorias: ['cat-1'],           dataCriacao: '2026-01-05', usuarioCriacao: 'Silvio Ventura' },
  { id: 3,  codigo: '1.1.01',  descricao: 'Grãos e Cereais',                condicao: 'credito', classe: 'analitica', ativo: 'sim', tipo: '',      antecessorId: 2,    categorias: ['cat-1', 'cat-1-1'], dataCriacao: '2026-01-05', usuarioCriacao: 'Silvio Ventura' },
  { id: 4,  codigo: '1.1.02',  descricao: 'Fruticultura',                   condicao: 'credito', classe: 'analitica', ativo: 'sim', tipo: '',      antecessorId: 2,    categorias: ['cat-1', 'cat-1-2'], dataCriacao: '2026-01-06', usuarioCriacao: 'Silvio Ventura' },
  { id: 5,  codigo: '1.2',     descricao: 'Receitas da Pecuária',           condicao: 'credito', classe: 'sintetica', ativo: 'sim', tipo: '',      antecessorId: 1,    categorias: ['cat-3'],           dataCriacao: '2026-01-06', usuarioCriacao: 'Silvio Ventura' },
  { id: 6,  codigo: '1.2.01',  descricao: 'Bovinocultura de Corte',         condicao: 'credito', classe: 'analitica', ativo: 'sim', tipo: '',      antecessorId: 5,    categorias: ['cat-3', 'cat-3-6'], dataCriacao: '2026-01-06', usuarioCriacao: 'Silvio Ventura' },
  { id: 7,  codigo: '1.2.02',  descricao: 'Bovinocultura de Leite',         condicao: 'credito', classe: 'analitica', ativo: 'sim', tipo: '',      antecessorId: 5,    categorias: ['cat-3', 'cat-3-10'], dataCriacao: '2026-01-07', usuarioCriacao: 'Silvio Ventura' },
  { id: 8,  codigo: '2',       descricao: 'Despesas',                      condicao: 'debito',  classe: 'sintetica', ativo: 'sim', tipo: '',      antecessorId: null, categorias: [],                  dataCriacao: '2026-01-05', usuarioCriacao: 'Silvio Ventura' },
  { id: 9,  codigo: '2.1',     descricao: 'Despesas Operacionais',         condicao: 'debito',  classe: 'sintetica', ativo: 'sim', tipo: '',      antecessorId: 8,    categorias: [],                  dataCriacao: '2026-01-05', usuarioCriacao: 'Silvio Ventura' },
  { id: 10, codigo: '2.1.01',  descricao: 'Insumos Agrícolas',              condicao: 'debito',  classe: 'analitica', ativo: 'sim', tipo: 'opex',  antecessorId: 9,    categorias: ['cat-34'],          dataCriacao: '2026-01-08', usuarioCriacao: 'Silvio Ventura' },
  { id: 11, codigo: '2.1.02',  descricao: 'Mão de Obra Rural',              condicao: 'debito',  classe: 'analitica', ativo: 'sim', tipo: 'opex',  antecessorId: 9,    categorias: ['cat-28'],          dataCriacao: '2026-01-08', usuarioCriacao: 'Silvio Ventura' },
  { id: 12, codigo: '2.1.03',  descricao: 'Combustível e Lubrificantes',    condicao: 'debito',  classe: 'analitica', ativo: 'sim', tipo: 'opex',  antecessorId: 9,    categorias: ['cat-21'],          dataCriacao: '2026-01-09', usuarioCriacao: 'Silvio Ventura' },
  { id: 13, codigo: '2.2',     descricao: 'Despesas Administrativas',      condicao: 'debito',  classe: 'sintetica', ativo: 'sim', tipo: '',      antecessorId: 8,    categorias: ['cat-16'],          dataCriacao: '2026-01-05', usuarioCriacao: 'Silvio Ventura' },
  { id: 14, codigo: '2.2.01',  descricao: 'Salários e Encargos',            condicao: 'debito',  classe: 'analitica', ativo: 'sim', tipo: 'opex',  antecessorId: 13,   categorias: ['cat-28', 'cat-28-1'], dataCriacao: '2026-01-10', usuarioCriacao: 'Silvio Ventura' },
  { id: 15, codigo: '2.2.02',  descricao: 'Aluguel e Arrendamento',         condicao: 'debito',  classe: 'analitica', ativo: 'nao', tipo: 'opex',  antecessorId: 13,   categorias: ['cat-16', 'cat-16-3'], dataCriacao: '2026-01-10', usuarioCriacao: 'Silvio Ventura' },
  { id: 16, codigo: '3',       descricao: 'Investimentos',                  condicao: 'ambos',   classe: 'sintetica', ativo: 'sim', tipo: '',      antecessorId: null, categorias: [],                  dataCriacao: '2026-01-05', usuarioCriacao: 'Silvio Ventura' },
  { id: 17, codigo: '3.1',     descricao: 'Máquinas e Equipamentos',        condicao: 'debito',  classe: 'sintetica', ativo: 'sim', tipo: '',      antecessorId: 16,   categorias: [],                  dataCriacao: '2026-01-05', usuarioCriacao: 'Silvio Ventura' },
  { id: 18, codigo: '3.1.01',  descricao: 'Tratores e Colheitadeiras',      condicao: 'debito',  classe: 'analitica', ativo: 'sim', tipo: 'capex', antecessorId: 17,   categorias: ['cat-50', 'cat-50-1'], dataCriacao: '2026-01-11', usuarioCriacao: 'Silvio Ventura' },
  { id: 19, codigo: '3.1.02',  descricao: 'Implementos Agrícolas',          condicao: 'debito',  classe: 'analitica', ativo: 'sim', tipo: 'capex', antecessorId: 17,   categorias: ['cat-50', 'cat-50-2'], dataCriacao: '2026-01-12', usuarioCriacao: 'Silvio Ventura' },
  { id: 20, codigo: '4',       descricao: 'Contas Patrimoniais',            condicao: 'ambos',   classe: 'sintetica', ativo: 'sim', tipo: '',      antecessorId: null, categorias: [],                  dataCriacao: '2026-01-05', usuarioCriacao: 'Silvio Ventura' },
]
