import type { Produto } from './produtos.types'

export const mockProdutos: Produto[] = [
  {
    id: 1, codigo: '05499',
    descricao: 'ELEMENTO FILTRANTE HIDRÁULICO - PH175',
    ncm: '84212300', unidadePrimaria: 'un', unidadeSecundaria: '', fatorConversao: '',
    grupoId: 1, categoriaId: 3, classeId: 2, variedadeId: '',
    controlaEstoque: true, estoqueMinimo: 5, controlaLote: false, controlaQualidade: false,
    precoMedio: 87.50, valorReferencia: 85.00, catFinanceiraId: '2',
    tipo: 'insumo', ativo: false, apontamento: false,
    principioAtivo: '', adicionaInventario: true, emitirNFe: false, dtUltCompra: '2024-11-20',
  },
  {
    id: 2, codigo: '05752',
    descricao: 'ELEMENTO FILTRO DO AR MOTOR - JOHN DEERE 7200',
    ncm: '84212300', unidadePrimaria: 'un', unidadeSecundaria: '', fatorConversao: '',
    grupoId: 1, categoriaId: 3, classeId: 2, variedadeId: '',
    controlaEstoque: true, estoqueMinimo: 3, controlaLote: false, controlaQualidade: false,
    precoMedio: 145.00, valorReferencia: 140.00, catFinanceiraId: '2',
    tipo: 'insumo', ativo: false, apontamento: false,
    principioAtivo: '', adicionaInventario: true, emitirNFe: false, dtUltCompra: '2024-10-15',
  },
  {
    id: 3, codigo: '00234',
    descricao: 'HERBICIDA GLIFOSATO 480 G/L',
    ncm: '38089390', unidadePrimaria: 'L', unidadeSecundaria: '', fatorConversao: '',
    grupoId: 2, categoriaId: 5, classeId: 6, variedadeId: '',
    controlaEstoque: true, estoqueMinimo: 20, controlaLote: true, controlaQualidade: true,
    precoMedio: 18.90, valorReferencia: 18.50, catFinanceiraId: '4',
    tipo: 'insumo', ativo: true, apontamento: true,
    principioAtivo: 'Glifosato', adicionaInventario: true, emitirNFe: true, dtUltCompra: '2025-02-10',
  },
  {
    id: 4, codigo: '00891',
    descricao: 'FUNGICIDA OPERA 500 EC',
    ncm: '38082000', unidadePrimaria: 'L', unidadeSecundaria: '', fatorConversao: '',
    grupoId: 2, categoriaId: 4, classeId: 5, variedadeId: '',
    controlaEstoque: true, estoqueMinimo: 10, controlaLote: true, controlaQualidade: true,
    precoMedio: 110.00, valorReferencia: 108.00, catFinanceiraId: '4',
    tipo: 'insumo', ativo: true, apontamento: true,
    principioAtivo: 'Epoxiconazol + Piraclostrobina', adicionaInventario: true, emitirNFe: true, dtUltCompra: '2025-01-28',
  },
  {
    id: 5, codigo: '01102',
    descricao: 'ADUBO FORMULADO NPK 00-20-20',
    ncm: '31051000', unidadePrimaria: 'sc', unidadeSecundaria: 'kg', fatorConversao: 60,
    grupoId: 3, categoriaId: 7, classeId: 8, variedadeId: '',
    controlaEstoque: true, estoqueMinimo: 50, controlaLote: false, controlaQualidade: false,
    precoMedio: 225.00, valorReferencia: 220.00, catFinanceiraId: '5',
    tipo: 'insumo', ativo: true, apontamento: true,
    principioAtivo: '', adicionaInventario: true, emitirNFe: true, dtUltCompra: '2025-03-05',
  },
  {
    id: 6, codigo: '01203',
    descricao: 'ADUBO UREIA 46%',
    ncm: '31021000', unidadePrimaria: 'sc', unidadeSecundaria: 'kg', fatorConversao: 60,
    grupoId: 3, categoriaId: 7, classeId: 9, variedadeId: '',
    controlaEstoque: true, estoqueMinimo: 40, controlaLote: false, controlaQualidade: false,
    precoMedio: 175.00, valorReferencia: 170.00, catFinanceiraId: '5',
    tipo: 'insumo', ativo: true, apontamento: true,
    principioAtivo: '', adicionaInventario: true, emitirNFe: true, dtUltCompra: '2025-03-01',
  },
  {
    id: 7, codigo: '02001',
    descricao: 'ÓLEO DIESEL S-10 GRANEL',
    ncm: '27101259', unidadePrimaria: 'L', unidadeSecundaria: '', fatorConversao: '',
    grupoId: 4, categoriaId: 9, classeId: 10, variedadeId: '',
    controlaEstoque: true, estoqueMinimo: 500, controlaLote: false, controlaQualidade: false,
    precoMedio: 5.90, valorReferencia: 5.85, catFinanceiraId: '3',
    tipo: 'insumo', ativo: true, apontamento: true,
    principioAtivo: '', adicionaInventario: false, emitirNFe: false, dtUltCompra: '2025-04-10',
  },
  {
    id: 8, codigo: '02100',
    descricao: 'ÓLEO MOTOR SAE 15W40 MINERAL',
    ncm: '27101921', unidadePrimaria: 'L', unidadeSecundaria: '', fatorConversao: '',
    grupoId: 4, categoriaId: 10, classeId: 11, variedadeId: '',
    controlaEstoque: true, estoqueMinimo: 20, controlaLote: false, controlaQualidade: false,
    precoMedio: 22.50, valorReferencia: 22.00, catFinanceiraId: '3',
    tipo: 'insumo', ativo: true, apontamento: false,
    principioAtivo: '', adicionaInventario: true, emitirNFe: false, dtUltCompra: '2025-02-18',
  },
  {
    id: 9, codigo: '03050',
    descricao: 'SEMENTE SOJA BMX POTÊNCIA RR — SC 40KG',
    ncm: '12010090', unidadePrimaria: 'sc', unidadeSecundaria: 'kg', fatorConversao: 40,
    grupoId: 6, categoriaId: 13, classeId: 14, variedadeId: 1,
    controlaEstoque: true, estoqueMinimo: 100, controlaLote: true, controlaQualidade: true,
    precoMedio: 380.00, valorReferencia: 375.00, catFinanceiraId: '6',
    tipo: 'insumo', ativo: true, apontamento: true,
    principioAtivo: '', adicionaInventario: true, emitirNFe: true, dtUltCompra: '2024-09-20',
  },
  {
    id: 10, codigo: '03051',
    descricao: 'SEMENTE SOJA TMG 7062 IPRO — SC 50KG',
    ncm: '12010090', unidadePrimaria: 'sc', unidadeSecundaria: 'kg', fatorConversao: 50,
    grupoId: 6, categoriaId: 13, classeId: 14, variedadeId: 2,
    controlaEstoque: true, estoqueMinimo: 80, controlaLote: true, controlaQualidade: true,
    precoMedio: 420.00, valorReferencia: 415.00, catFinanceiraId: '6',
    tipo: 'insumo', ativo: true, apontamento: true,
    principioAtivo: '', adicionaInventario: true, emitirNFe: true, dtUltCompra: '2024-09-20',
  },
  {
    id: 11, codigo: '04100',
    descricao: 'INSETICIDA KARATE ZEON 50 CS',
    ncm: '38081900', unidadePrimaria: 'L', unidadeSecundaria: '', fatorConversao: '',
    grupoId: 2, categoriaId: 6, classeId: 1, variedadeId: '',
    controlaEstoque: true, estoqueMinimo: 8, controlaLote: true, controlaQualidade: false,
    precoMedio: 95.00, valorReferencia: 92.00, catFinanceiraId: '4',
    tipo: 'insumo', ativo: true, apontamento: true,
    principioAtivo: 'Lambda-cialotrina', adicionaInventario: true, emitirNFe: true, dtUltCompra: '2025-01-15',
  },
  {
    id: 12, codigo: '04250',
    descricao: 'PARAFUSO SEXTAVADO M12 X 40 ZINCADO',
    ncm: '84314900', unidadePrimaria: 'un', unidadeSecundaria: '', fatorConversao: '',
    grupoId: 5, categoriaId: 11, classeId: 13, variedadeId: '',
    controlaEstoque: true, estoqueMinimo: 50, controlaLote: false, controlaQualidade: false,
    precoMedio: 1.20, valorReferencia: 1.15, catFinanceiraId: '7',
    tipo: 'insumo', ativo: true, apontamento: false,
    principioAtivo: '', adicionaInventario: false, emitirNFe: false, dtUltCompra: '2025-03-22',
  },
  {
    id: 13, codigo: '04251',
    descricao: 'CORREIA POLY-V 6PK 1860 — COLHEITADEIRA',
    ncm: '84314900', unidadePrimaria: 'un', unidadeSecundaria: '', fatorConversao: '',
    grupoId: 5, categoriaId: 11, classeId: 13, variedadeId: '',
    controlaEstoque: true, estoqueMinimo: 2, controlaLote: false, controlaQualidade: false,
    precoMedio: 320.00, valorReferencia: 315.00, catFinanceiraId: '2',
    tipo: 'insumo', ativo: true, apontamento: false,
    principioAtivo: '', adicionaInventario: true, emitirNFe: false, dtUltCompra: '2025-02-05',
  },
  {
    id: 14, codigo: '05001',
    descricao: 'CLORETO DE POTÁSSIO — GRANULADO',
    ncm: '31042000', unidadePrimaria: 'sc', unidadeSecundaria: 'kg', fatorConversao: 60,
    grupoId: 3, categoriaId: 7, classeId: 8, variedadeId: '',
    controlaEstoque: true, estoqueMinimo: 60, controlaLote: false, controlaQualidade: false,
    precoMedio: 195.00, valorReferencia: 190.00, catFinanceiraId: '5',
    tipo: 'insumo', ativo: true, apontamento: true,
    principioAtivo: '', adicionaInventario: true, emitirNFe: true, dtUltCompra: '2025-03-10',
  },
  {
    id: 15, codigo: '05100',
    descricao: 'LUBRIFICANTE TRANSMISSÃO JOHN DEERE HY-GARD',
    ncm: '27101921', unidadePrimaria: 'L', unidadeSecundaria: '', fatorConversao: '',
    grupoId: 4, categoriaId: 10, classeId: 12, variedadeId: '',
    controlaEstoque: true, estoqueMinimo: 10, controlaLote: false, controlaQualidade: false,
    precoMedio: 38.00, valorReferencia: 36.50, catFinanceiraId: '3',
    tipo: 'insumo', ativo: true, apontamento: false,
    principioAtivo: '', adicionaInventario: false, emitirNFe: false, dtUltCompra: '2025-01-30',
  },
]
